---

- hosts: docker-1
  remote_user: sattvika
  gather_facts: false   # don't gather facts yet in case if python 2 isn't installed yet
  become: true

  pre_tasks:
    - name: install python2 for Ansible if not installed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: pyinstall_output
      changed_when: pyinstall_output.stdout != ""

    - setup: # this run gather_facts

  roles:
    - role: ANXS.postgresql
      postgresql_version: 9.6
      postgresql_admin_user: "postgres"
      postgresql_default_auth_method: "md5"
      postgresql_pg_hba_default:
        - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: 'trust', comment: 'Always use trust method for local connection' }
        - { type: local, database: all, user: 'ewallet', address: '', method: 'trust', comment: 'Always use trust method for local connection' }
        - { type: local, database: all, user: all, address: '', method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
        - { type: host,  database: all, user: all, address: '0.0.0.0/0', method: 'reject', comment: 'IPv4 local connections:' }
        - { type: host,  database: all, user: all, address: '::1/128', method: 'reject', comment: 'IPv6 local connections:' }
      postgresql_users:
        - name: ewallet
          pass: ewallet
          encrypted: no
      postgresql_databases:
        - name: ewallet
          owner: ewallet
          encoding: 'UTF-8'
      postgresql_user_privileges:
        - name: ewallet
          db: ewallet
          priv: "ALL"
          role_attr_flags: "CREATEDB"
  